<?php

/**
 * Implements hook_form_FORM_ID_alter()
 */
function print_extra_form_print_mail_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['fld_title'])) {
    $path = $form['path']['#value'];
    $nid = preg_replace('!^node/!', '', $path);
    if (ctype_digit($nid)) {
      $node = node_load($nid);
      $title_field_instance = title_field_replacement_get_label_field('node', $node->type);
      if (!empty($title_field_instance)) {
        // Get title field value
        $items = field_get_items('node', $node, $title_field_instance['field_name']);
        // Get renderable value having correctly formatter as per text format, if any.
        $title = field_view_value('node', $node, $title_field_instance['field_name'], $items[0]);
        // Set it as node title.
        $title = render($title);
        $form['title']['#value'] = $title;
        $form['fld_title']['#markup'] = l($title, $path, array('attributes' => array('title' => t('View page')), 'query' => $form['query']['#value'], 'html' => TRUE));
      }
    }
  }
}

/**
 * Implements hook_mail_alter()
 */
function print_extra_mail_alter(&$message) {
  if ($message['id'] == 'print_mail_sendlink') {
    if (module_exists('mimemail' ) && !class_exists('Mail_mime')) {
      // Rest body
      $message['body'] = array();
      // @see theme_print_mail_sendlink_html()
      // Just override to generate link with HTML tags.
      $message['body'][] = $message['params']['message'] . '<br/><br/>' . l($message['params']['title'], $message['params']['link'], array('html' => TRUE));;
      // Remove 'Content-type' set by print_mail module.
      unset($message['headers']['Content-Type']);
    }
  }
}

/**
 * Implements hook_widgets_element_info().
 */
function print_extra_widgets_element_info() {
  $elements = array(
    'print-printmail' => array(
      'label' => t('Print email a friend button'),
      'group' => t('Print'),
      'template' => '<a class="" href=""><img src="[?icon-path=[socialmedia:sm-email_icon-path]?]" alt="e-mail icon XXX" ></a>',
      'view callback' => 'print_extra_printmail_element_view',
    ),
  );
  return $elements;
}

function print_extra_printmail_element_view($element) {
  return str_replace('href=""', 'href="' . url('printmail/' . drupal_lookup_path('alias', current_path())) . '"', $element['template']);
}
