<?php

/**
 * Implements hook_menu().
 */
function print_extra_menu() {
  $items = array();
  $items['admin/config/user-interface/print/extra'] = array(
    'title' => 'Extra Settings',
    'description' => 'Settings for the extra functionalities for all the print sub-modules.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('print_extra_settings'),
    'access arguments'  => array('administer print'),
    'weight' => 15,
    'type' => MENU_LOCAL_TASK,
    'file' => 'print_extra.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_alter()
 */
function print_extra_menu_alter(&$items) {
  if (module_exists('print_mail')) {
    $link = print_mail_print_link();
    if (isset($items[$link['path']])) {
      // Set menu title to custom entered value if user configured it for the "Send by email" link.
      $items[$link['path']]['title'] = variable_get('print_' . $link['format'] . '_link_text', $link['text']);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function print_extra_form_print_mail_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['fld_title'])) {
    $path = $form['path']['#value'];
    $nid = preg_replace('!^node/!', '', $path);
    if (ctype_digit($nid)) {
      $node = node_load($nid);
      $title_field_instance = title_field_replacement_get_label_field('node', $node->type);
      if (!empty($title_field_instance)) {
        // Get title field value
        $items = field_get_items('node', $node, $title_field_instance['field_name']);
        // Get renderable value having correctly formatter as per text format, if any.
        $title = field_view_value('node', $node, $title_field_instance['field_name'], $items[0]);
        // Set it as node title.
        $title = render($title);
        $form['title']['#value'] = $title;
        $form['fld_title']['#markup'] = l($title, $path, array('attributes' => array('title' => t('View page')), 'query' => $form['query']['#value'], 'html' => TRUE));
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter()
 */
function print_extra_form_print_mail_settings_alter(&$form, &$form_state, $form_id) {
  // 'print_mail_link_text' is now being used for menu title by print_extra_menu_alter().
  // Let admin know that cache need to be cleared to reflect the change on send by email page.
  $form['settings']['link_text']['print_mail_link_text']['#description'] .= t(' Clear menu cache to make it reflect on "Send by email" page title.');
}

/**
 * Implements hook_mail_alter()
 */
function print_extra_mail_alter(&$message) {
  if ($message['id'] == 'print_mail_sendlink') {
    if (module_exists('mimemail' ) && !class_exists('Mail_mime')) {
      // Rest body
      $message['body'] = array();
      // @see theme_print_mail_sendlink_html()
      // Just override to generate link with HTML tags.
      $message['body'][] = $message['params']['message'] . '<br/><br/>' . l($message['params']['title'], $message['params']['link'], array('html' => TRUE));;
      // Remove 'Content-type' set by print_mail module.
      unset($message['headers']['Content-Type']);
    }
  }
}

/**
 * Implements hook_widgets_element_info().
 */
function print_extra_widgets_element_info() {
  $elements = array(
    'print-printmail' => array(
      'label' => t('Print email a friend button'),
      'group' => t('Print'),
      'template' => '<a class="" href=""><img src="[?icon-path=[socialmedia:sm-email_icon-path]?]" alt="e-mail icon XXX" ></a>',
      'view callback' => 'print_extra_printmail_element_view',
    ),
  );
  return $elements;
}

function print_extra_printmail_element_view($element) {
  return str_replace('href=""', 'href="' . url('printmail/' . drupal_lookup_path('alias', current_path())) . '"', $element['template']);
}

/**
 * Implements hook_preprocess_HOOK()
 */
function print_extra_preprocess_print_url_list(&$variables) {
  global $base_url;
  $base_urls = array($base_url);

  $pages_to_exclude = preg_split ('/$\R?^/m', variable_get('print_extra_url_list_filter', ''));
  $urls = &drupal_static('_print_friendly_urls', array());
  // Find URL scheme. HTTP or HTTPS?
  preg_match('~^(https?)://~', $base_url, $match);
  // Prepare secure or non-secure alternative.
  if ($match[1] == 'http') {
    $base_urls[] = preg_replace('~^http~', 'https', $base_url);
  }
  elseif ($match[1] == 'https') {
    $base_urls[] = preg_replace('~^https~', 'http', $base_url);
  }

  $internal = array();
  module_load_include('inc', 'print_extra', 'includes/print_extra.util');
  foreach ($urls as $index => $url) {
    $internal_path = NULL;
    // Find internal path fom absolute path.
    if (($pos = strpos($url, $base_urls[0])) === 0) {
      $internal_path = substr($url, strlen($base_urls[0]));
    }
    elseif ( ( $pos = strpos($url, $base_urls[1])) === 0) {
      $internal_path = substr($url, strlen($base_urls[1]));
    }
    if ($internal_path) {
      // Remove leading slash.
      $internal_path = ltrim($internal_path, '/');
      if (print_extra_match_path($internal_path, $pages_to_exclude)) {
        // It matches with configured patterns to be excluded.
        // Thus remove URL from list.
        unset($urls[$index]);
      }
    }
  }
}
